"""Sphinx configuration for the polyxios documentation site.

Retro terminal theme layered on top of pydata-sphinx-theme:
  * light mode  = "paper"  (warm cream, ink text)
  * dark mode   = "crt"    (amber phosphor on near-black)

Both palettes live in _static/css/retro.css as pydata theme variables, so the
theme's own light/dark switcher in the navbar drives them.

The only custom JavaScript is _static/js/homepage.js, which drives the copy
button on the landing page's install command.
"""

import os
import sys
from importlib import metadata
from pathlib import Path

from packaging.version import Version

import polyxios

# docs/_ext holds the small in-tree extensions, such as the credits generator.
sys.path.insert(0, str(Path(__file__).parent / "_ext"))

project = "polyxios"
author = "polyxios contributors"
copyright = "2026, polyxios contributors"
release = getattr(polyxios, "__version__", None) or metadata.version("polyxios")

# "0.3.0.dev0+git..." -> the "0.3" series.
_parsed = Version(release)
version = f"{_parsed.major}.{_parsed.minor}"
_is_dev = _parsed.is_devrelease or _parsed.local is not None

# The switcher entry this build should highlight. A dev build off master is
# "dev"; a tagged build is its own "X.Y" series. SWITCHER_VERSION lets a
# release job pin it explicitly.
switcher_version = os.environ.get("SWITCHER_VERSION") or ("dev" if _is_dev else version)

# The site's own home. Not the github.io address, which only 301s here.
# Canonical links, the sitemap and switcher.json must all name the final URL.
SITE_URL = os.environ.get("SITE_URL", "https://polyxios.org")

# The published switcher index. It must be an absolute URL so it resolves the
# same from every page depth. It is generated on the gh-pages branch by
# tools/gen_switcher.py from the version directories actually deployed, so it
# can never offer a version that does not exist. SWITCHER_JSON_URL points a
# local build somewhere else.
switcher_json_url = os.environ.get(
    "SWITCHER_JSON_URL", f"{SITE_URL.rstrip('/')}/switcher.json"
)

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "numpydoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.extlinks",
    "sphinx_copybutton",
    "sphinxext.opengraph",
    "sphinx_sitemap",
    "contributors",
    "seo",
]

# The credits page names these by hand; everyone else in the git history is
# listed under "Contributors", generated by the contributors extension.
polyxios_core_developers = [
    "Serge Koudoro",
    "Praneeth Shetty",
    "Maharshi Gor",
]

# -- SEO / answer engines ---------------------------------------------------

TAGLINE = "Fast, clean 3D mesh and geometry file I/O for Python."

# Every version of a page is published at /dev/, /stable/ and /X.Y/. Canonical
# links point all of them at the stable copy so search engines rank one URL
# instead of splitting between three; docs/_ext/seo.py additionally marks
# non-stable builds noindex.
html_baseurl = f"{SITE_URL.rstrip('/')}/stable/"

# True only for the build that becomes /stable/, i.e. the newest release.
polyxios_is_stable = os.environ.get("DOCS_IS_STABLE", "").lower() in {"1", "true", "yes"}
polyxios_tagline = TAGLINE

# sphinx-sitemap needs these two; the {version}/{lang} placeholders are unused
# because each version is built and deployed on its own.
sitemap_url_scheme = "{link}"

# sphinxext-opengraph: social cards, and the plain <meta name="description">
# that Sphinx does not emit on its own.
ogp_site_url = html_baseurl
ogp_site_name = "polyxios"
ogp_description_length = 200
ogp_enable_meta_description = True
ogp_type = "website"

# Social preview cards are rendered at build time (needs the [social-cards]
# extra, which pulls matplotlib). Colours track the CRT palette in retro.css.
ogp_social_cards = {
    "enable": True,
    "site_url": SITE_URL,
    "line_color": "#ffb02e",
}

extlinks = {
    "ghpull": ("https://github.com/fury-gl/polyxios/pull/%s", "PR #%s"),
    "ghissue": ("https://github.com/fury-gl/polyxios/issues/%s", "GH#%s"),
}

autosummary_generate = True
numpydoc_show_class_members = False

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable", None),
}

exclude_patterns = ["_build", "_includes", "_templates"]

# -- HTML output ------------------------------------------------------------

html_theme = "pydata_sphinx_theme"
html_title = "polyxios"
html_static_path = ["_static"]
templates_path = ["_templates"]
html_css_files = ["css/retro.css"]
html_js_files = ["js/homepage.js"]

html_theme_options = {
    # The retro palettes are tuned against these two.
    "pygments_light_style": "friendly",
    "pygments_dark_style": "native",
    # Escaped: pydata drops the logo text into the template unescaped, so a raw
    # "<polyxios />" is parsed as an unknown HTML element and renders nothing.
    "logo": {"text": "&lt;polyxios /&gt;"},
    "announcement": (
        "// fast, clean mesh I/O for Python - one dependency instead of twenty-five"
    ),
    "github_url": "https://github.com/fury-gl/polyxios",
    "icon_links": [
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/polyxios/",
            "icon": "fa-solid fa-box",
        },
        {
            "name": "FURY",
            "url": "https://fury.gl",
            "icon": "fa-solid fa-cube",
        },
    ],
    # Version switcher. json_url must be absolute so it resolves the same from
    # every page depth; check_switcher stays off so a build without network
    # access (local, or a PR runner) does not fail under -W.
    "switcher": {
        "json_url": switcher_json_url,
        "version_match": switcher_version,
    },
    "check_switcher": False,
    "show_version_warning_banner": True,
    "navbar_start": ["navbar-logo"],
    "navbar_center": ["navbar-nav"],
    "navbar_end": ["version-switcher", "py-version", "theme-switcher", "navbar-icon-links"],
    "navbar_persistent": ["search-button"],
    "navbar_align": "left",
    "secondary_sidebar_items": ["page-toc", "edit-this-page"],
    "show_prev_next": True,
    # _templates/sidebar-nav-bs.html renders the toctree from depth 0, so every
    # page carries the whole documentation tree. Top-level entries are always
    # visible; sections with children (formats, api) expand on click, and the
    # section containing the current page is expanded on load. Raising this to 2
    # expands everything but drops the toggles entirely, which loses the
    # collapse affordance on the twenty-five format pages.
    "show_nav_level": 1,
    "navigation_depth": 3,
    "collapse_navigation": False,
    "navigation_with_keys": False,
    "footer_start": ["copyright"],
    "footer_end": ["last-updated"],
    "use_edit_page_button": True,
}

html_context = {
    "github_user": "fury-gl",
    "github_repo": "polyxios",
    "github_version": "master",
    "doc_path": "docs",
    # Start visitors in the CRT palette; the navbar switcher still works.
    "default_mode": "dark",
}

# The landing page is full-bleed: no primary sidebar, no page-toc.
html_sidebars = {"index": []}

html_last_updated_fmt = "%Y-%m-%d"
copybutton_prompt_text = r"\$ |>>> "
copybutton_prompt_is_regex = True
